version: '1.0'

services:
  spark-master:
    image: bitnami/spark:3.5
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080" # Spark Web UI
      - "7077:7077" # Spark Master Port
    volumes:
      - ./data:/opt/spark-apps/data
      - ./scripts:/opt/spark-apps/scripts

  spark-worker:
    image: bitnami/spark:3.5
    hostname: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_CORES=6
      - SPARK_WORKER_MEMORY=6G
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
